# Site settings
title: Silas | Digital Designer
email: hello@patrickrogan.co
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
permalink: "/:title"
twitter_username: heyiamsilas
github_username:  silaswanders

# Build settings
markdown: kramdown
sass:
sass_dir: _sass
style: compressed
